sudo: required
services:
  - docker

before_install:
  - docker build -t jbvdmerwe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbvdmerwe/react-test npm test

after_success:
  - docker build -t jbvdmerwe/multi-client ./client
  - docker build -t jbvdmerwe/multi-nginx ./nginx
  - docker build -t jbvdmerwe/multi-server ./server
  - docker build -t jbvdmerwe/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push jbvdmerwe/multi-client
  - docker push jbvdmerwe/multi-nginx
  - docker push jbvdmerwe/multi-server
  - docker push jbvdmerwe/multi-worker